### PR TITLE
Added hatchmap function

### PR DESCRIPTION
**Pull request by sarahclaude**
Function to add hatching over maps using matplotlib contourf.

### CODE REVIEW

**Comment by sarahclaude** [comment]
I am trying to commit a file with the line (1965):

im = v.where(mask == True).plot.contourf(ax=ax, transform=transform, **plot_kw[k])

but the commits fails with :
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
figanos/matplotlib/plot.py:1965:31: E712 comparison to True should be 'if cond is True:' or 'if cond:'

Should I change the .where(mask==True)? @Zeitsperre

**Comment by Zeitsperre** [comment]
You should change it, yes. This is kind of an interesting read on why `==True` is not a good idea, particularly in Python.

If the values of mask are a boolean array, `mask is True` is more Pythonic. Otherwise, if we are concerned about the "Truthyness" of `mask` (i.e. positive integers/floats), you can just use `mask`.

**Comment by sarahclaude** [comment]
Thanks!

**Comment by sarahclaude** [comment]
<p>Levels est directement envoyer a matplotlib.contourf (If an int&nbsp;<em>n</em>, use&nbsp;<code><a href="https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.MaxNLocator" target="_blank">MaxNLocator</a></code>, which tries to automatically choose no more than&nbsp;<em>n+1</em>&nbsp;"nice" contour levels between minimum and maximum numeric values of&nbsp;<em>Z</em>.</p><p>If array-like, draw contour lines at the specified levels. The values must be in increasing order). </p><p> </p><p>Donc, c'est matplotlib qui gère le tout puisque je n'ai pas fait de fonction propre à figanos comme Alexis avait fait pour Gridmap et je n'ai pas spécifier d'intervalles.</p><p> </p><p>Je penses effectivement que levels pourrait être retirer des arguments et si qqn veut l'utiliser ce sera une option de plot_kw. Est-ce que j'enlève l'exemple aussi? </p><p> </p><p>Sinon, l'autre option ce serait de créer qqc de similaire à gridmap pour les niveaux.</p>

---

 <a href='https://app.reviewnb.com/Ouranosinc/figanos/pull/107/discussion/#comment-1668479749'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by juliettelavoie — APPROVED** [review]

**Pull request merged**
