### PR TITLE
Cookiecutter update, support Python3.12, drop Python3.8

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
  - This PR fixes #xyz
- [x] (If applicable) Documentation has been added / updated (for bug fixes / features).
- [ ] (If applicable) Tests have been added.
- [x] CHANGES.rst has been updated (with summary of main changes).
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.

### What kind of change does this PR introduce?

* `figanos` now supports Python3.12 and no longer supports Python3.8
* Updates the template to the latest commit
* GitHub Workflows now point to commits rather than tags
* Dependabot will now only update on a monthly schedule
* Dependencies have been updated and synchronized 
* `twine` and `wheel` have been removed (redundant)
* Added a `CODE_OF_CONDUCT.rst` file adapting Contributor Covenant v2.1

### Does this PR introduce a breaking change?

Yes.

* `cartopy` pin has been raised to v0.23.0 due to a licensing issue
* The maximum supported version of Python has been raised to 3.12 (expanded dependency support).
* The minimum supported version of Python has been raised to 3.9 (due to `cartopy`).
* `CHANGES.rst` is now `CHANGELOG.rst`
* The package now uses a `src` layout in lieu of a `flat` layout
* Maintainer-specific directions are now found under `releasing.rst`

> [!WARNING]  
> The changes to the package structure requires you to fully reinstall the library using `pip install -e .`
> This is almost like installing a brand new library, except it's virtually the same.

### Other information:

https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/
https://keepachangelog.com/en/1.0.0/

### CODE REVIEW

**Comment by sarahclaude** [comment]
The import inside figanos docs are not working. 
How should we adjust imports with the src directory (it seems like it might also be the __init__.py that are not working)

**Comment by Zeitsperre** [comment]
@sarahclaude 

It looks like we're using absolute paths:
```python 
with open(str(Path(os.getcwd()).parents[1])+ "/figanos/data/ipcc_colors/variable_groups.json") as f:
    var_dict = json.load(f)
for f in np.sort(glob.glob(str(Path(os.getcwd()).parents[1])+ "/figanos/data/ipcc_colors/continuous_colormaps_rgb_0-255/*")):
    name=Path(f).name.replace('.txt','')
    ...
```

Would it make sense to expose these files using a function?

**Comment by sarahclaude** [comment]
Sure, we could!

```
def get_mpl_styles() -> dict[str, str]:
    """Get the available matplotlib styles and their paths, as a dictionary."""
    folder = pathlib.Path(__file__).parent / "style/"
    paths = sorted(folder.glob("*.mplstyle"))
    names = [str(p).split("/")[-1].removesuffix(".mplstyle") for p in paths]
    styles = {str(name): path for name, path in zip(names, paths)}

    return styles
```

Is this alright due to using Pathlib instead of os.getcwd()?

**Comment by Zeitsperre** [comment]
I'm almost done with a Pull Request based off this branch. Will propose something very soon.

**Comment by Zeitsperre** [comment]
> @Zeitsperre I'm just curious, could you say a bit more on the advantage of using a `src` layout ? Aee you planning on changing the layout of xscen and xlim as well ?

Sure, the primary benefit is that in order to test the library, it must be installed (you can run `pytest` on non-installed libraries if the folder structure is flat). This makes it so that testing occurs on the library in a typical configuration.

The other benefit is that if let's say we wanted to offer two installable modules for our package, we can do that very easily (they would both live in `/src`).

`pyOpenSci` recommends that packages use a `/src` layout, and many of the major packages in the standard library are also moving to this layout style as well to simplify development/configuration (see: https://hynek.me/articles/testing-packaging/).

**Review by sarahclaude — APPROVED** [review]
It works well after reinstalling figanos. Thanks Trevor!

**Review by juliettelavoie — APPROVED** [review]
thanks!

**Pull request merged**
