### PR TITLE
Fix notebook

### PR DESCRIPTION
**Pull request by juliettelavoie**
- Fixed level of title in notebook to make docs better
- remove double cartopy from env
- added the logo
- added a theme 
- updated history ( no link to issue, pr or user yet) don't know how to activate that

I am still having issues with warning when creating the docs. There two main types:
1. this appears for a lot of functions
```
figanos/figanos/matplotlib/plot.py:docstring of figanos.matplotlib.plot.gdfmap:4: CRITICAL: Unexpected section title.

Parameters
----------

```

2.
```

figanos/docs/notebooks/figanos_docs.ipynb:1177: WARNING: undefined label: /notebooks/figanos_docs.ipynb#gridmap
figanos/docs/notebooks/figanos_docs.ipynb:1523: WARNING: undefined label: /notebooks/figanos_docs.ipynb#gridmap
figanos/docs/notebooks/figanos_docs.ipynb:1757: WARNING: undefined label: /notebooks/figanos_docs.ipynb#gdfmap
figanos/docs/notebooks/figanos_docs.ipynb:1871: WARNING: undefined label: /notebooks/figanos_docs.ipynb#stripes
figanos/docs/notebooks/figanos_docs.ipynb:2013: WARNING: undefined label: /notebooks/figanos_docs.ipynb#violin
figanos/docs/notebooks/figanos_docs.ipynb:2105: WARNING: undefined label: /notebooks/figanos_docs.ipynb#heatmap
/figanos/docs/notebooks/figanos_docs.ipynb:2243: WARNING: undefined label: /notebooks/figanos_docs.ipynb#taylordiagram

```
@Zeitsperre any idea on what the problem is ?

### CODE REVIEW

**Comment by Zeitsperre** [comment]
Ahoy hoy,

> I am still having issues with warning when creating the docs. There two main types:
> 
>     1. this appears for a lot of functions
> ```
> figanos/figanos/matplotlib/plot.py:docstring of figanos.matplotlib.plot.gdfmap:4: CRITICAL: Unexpected section title.
> 
> Parameters
> ----------
> ```
This is because numpy-dcostring support in sphinx is made possible due to a sphinx extension (`sphinx.ext.napoleon`). We probably need to simply add that to the `conf.py` (built-in, no need to add deps).

> ```
> 
> figanos/docs/notebooks/figanos_docs.ipynb:1177: WARNING: undefined label: /notebooks/figanos_docs.ipynb#gridmap
> figanos/docs/notebooks/figanos_docs.ipynb:1523: WARNING: undefined label: /notebooks/figanos_docs.ipynb#gridmap
> figanos/docs/notebooks/figanos_docs.ipynb:1757: WARNING: undefined label: /notebooks/figanos_docs.ipynb#gdfmap
> figanos/docs/notebooks/figanos_docs.ipynb:1871: WARNING: undefined label: /notebooks/figanos_docs.ipynb#stripes
> figanos/docs/notebooks/figanos_docs.ipynb:2013: WARNING: undefined label: /notebooks/figanos_docs.ipynb#violin
> figanos/docs/notebooks/figanos_docs.ipynb:2105: WARNING: undefined label: /notebooks/figanos_docs.ipynb#heatmap
> /figanos/docs/notebooks/figanos_docs.ipynb:2243: WARNING: undefined label: /notebooks/figanos_docs.ipynb#taylordiagram
> ```

I think this has to do with the way that links are written within the documentation. It could be that Sphinx is mistaking them for tags to other sections. I'll take a look.

**Review by sarahclaude — APPROVED** [review]
Love the read the docs, looks super clean!

**Comment by sarahclaude** [comment]
In history, can the fix font size be smaller than the release (0.0.1)?

**Comment by sarahclaude** [comment]
There's an empty cell under "Station Data on Maps" in the gettint started.

**Comment by sarahclaude** [comment]
In Usage maybe change for:  
To use figanos matplotlib stylesheet with any matplotlib code

**Comment by Zeitsperre** [comment]
@sarahclaude Feel free to mark up changes within the notebooks using the review-notebook-app!

**Comment by juliettelavoie** [comment]
> In history, can the fix title font size be smaller than the release (0.0.1)?

I don't think so.. It seems to just be the theme doing that (https://sphinx-book-theme.readthedocs.io/en/latest/changelog.html). It is technically a subsection in the .rst file.

**Comment by sarahclaude** [comment]
Thank you Trevor, really useful app!

**Comment by Zeitsperre** [comment]
> > In history, can the fix title font size be smaller than the release (0.0.1)?
> 
> I don't think so.. It seems to just be the theme doing that (https://sphinx-book-theme.readthedocs.io/en/latest/changelog.html). It is technically a subsection in the .rst file.

It looks as though this theme accepts CSS overrides! https://pradyunsg.me/furo/customisation/

**Pull request merged**
